import type { Metadata } from "next";
// import "../../public/assets/style.css";
// import { Urbanist } from 'next/font/google';
import { Prompt } from 'next/font/google';

import "./globals.css"
import { ProvidersCustom } from "@/components/providers/ProvidersCustom";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const fontCustom = Prompt( {
	subsets: [ "latin" ],
	weight: [ "400" ],
} );

export default function RootLayout( { children }: Readonly<{ children: React.ReactNode; }> ) {
	return (
		<html lang={ "es" } suppressHydrationWarning>
		<body className={ `${ fontCustom.className } min-h-screen transition-colors duration-300` }
			  suppressHydrationWarning>
		<ProvidersCustom>
			{ children }
		</ProvidersCustom>
		</body>
		</html>
	);
}
